name: Print GitHub Token

on: 
  workflow_dispatch:

jobs:
  print-token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Temporarily disable masking
        run: echo "::add-mask::"

      - name: Print GitHub Token
        run: 'echo "GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}"'
